# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Samuel Sáez López — Universidad Politécnica de Cartagena
"""
Project — the central in-memory model of a slope-stability analysis.

This class is the *single source of truth* for the GUI, CLI, and solver.
It owns:
    - Geometry (boundaries, water surfaces, tension cracks)
    - Materials & supports
    - External loads
    - Analysis settings
    - Serialization (JSON) + results linkage (HDF5)

The class exposes a light observer API so that the GUI canvas can be
notified when the underlying model changes.

Author: Samuel Sáez López (UPCT)
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Callable, Optional
from uuid import uuid4

from ..geometry import Boundary, BoundaryType, Vertex
from ..loads import DistributedLoad, LineLoad, SeismicLoad
from ..materials import Material
from ..support import SupportInstance
from .settings import ProjectSettings

FILE_FORMAT_VERSION = "0.1"


class Project:
    """Container for all geotechnical data belonging to a single analysis."""

    def __init__(self, name: str = "Untitled") -> None:
        self.id: str = str(uuid4())
        self.name: str = name
        self.file_path: Optional[Path] = None
        self.is_dirty: bool = False

        self.settings: ProjectSettings = ProjectSettings()
        self.settings.summary.title = name
        self.settings.summary.date_created = datetime.utcnow().isoformat()

        # Model content
        self.boundaries: list[Boundary] = []
        self.materials: list[Material] = []
        self.supports: list[SupportInstance] = []
        # v0.1.14 — list of SupportType property definitions
        # (one per "Support type" the user has defined). Each
        # SupportInstance references one by ``type_id``.
        self.support_types: list = []
        self.distributed_loads: list[DistributedLoad] = []
        self.line_loads: list[LineLoad] = []
        self.seismic: SeismicLoad = SeismicLoad()
        # v0.1.23 — Water Pressure Grid (Phase 0 groundwater plan);
        # active when settings.groundwater.method is a GRID_* type.
        self.water_pressure_grid = None  # Optional[WaterPressureGrid]
        # v0.1.25 — FE mesh for the groundwater (seepage) analysis;
        # generated in Groundwater mode, consumed by OGR FEM2D.
        self.fem_mesh = None  # Optional[ogr_fem2d.mesh.Mesh]
        # v0.1.28 — converged seepage field feeding PorePressureType
        # .FEM_SEEPAGE. Not serialised: it is a computed result, and is
        # regenerated by re-running the groundwater analysis.
        self.seepage_result = None
        # v0.1.29 — seepage boundary conditions (edited in Groundwater
        # mode). Serialised so the model keeps them across sessions.
        self.seepage_bcs = None
        # v0.1.30 — per-stage transient results (computed, not saved)
        self.transient_results = []
        # v0.1.34 — random variables for the probabilistic / sensitivity
        # analysis (Phase P1). Serialised with the model.
        self.random_variables = []
        # v0.1.54 (phase M3) — the annotation layer. Deliberately a
        # SEPARATE list from ``boundaries``: the solver never reads it,
        # so a sketch cannot be mistaken for geometry and no analysis
        # result can change because someone drew on the model.
        from ..annotations import AnnotationLayer
        self.annotations = AnnotationLayer()
        # v0.1.55 (phase M4) — focus objects narrow the search. Stored on
        # the project because they are part of how the model is analysed,
        # not a transient view setting.
        self.focus_objects = []

        # v0.1.11 — Regions cache (avoids recomputing planar
        # subdivision for every material_at() lookup during compute).
        self._regions_cache: Optional[list] = None
        self._regions_cache_signature: Optional[tuple] = None
        # v0.1.11 — Bounding-box cache (used in early-skip checks)
        self._bbox_cache: Optional[tuple] = None
        self._bbox_cache_signature: Optional[tuple] = None

        # v0.1.6 — Region assignments (Slide-style material painting).
        # Each entry: {"x": float, "y": float, "material_id": str}.
        # Represents a user click on a material region. On every
        # geometry change, regions are recomputed by planar subdivision
        # (External ∪ Material Boundaries) and the assignments are
        # relocalised by point-in-polygon against the new regions.
        # This means the assignments survive edits such as moving
        # vertices or adding/removing material boundaries, as long as
        # the click-point still lies inside a valid region.
        self.region_assignments: list[dict] = []

        # v0.1.7 — Tension Crack hydraulic properties (defaults: Filled,
        # the worst case in Slide). Only applies if a Tension Crack
        # boundary exists in the project.
        from ..geometry.tension_crack import TensionCrackProperties
        self.tension_crack_properties: TensionCrackProperties = (
            TensionCrackProperties()
        )

        # Results path (HDF5 companion file, same stem as project)
        self.results_path: Optional[Path] = None

        # Observer hooks
        self._listeners: list[Callable[[str], None]] = []

    # ------------------------------------------------------------------
    # Observer API
    # ------------------------------------------------------------------
    def add_listener(self, cb: Callable[[str], None]) -> None:
        self._listeners.append(cb)

    def _notify(self, event: str) -> None:
        self.is_dirty = True
        # v0.1.11 — auto-invalidate caches on any model mutation that
        # could affect regions or bbox.
        if event in (
            "boundary_added", "boundary_removed", "boundary_modified",
            "material_added", "material_removed", "material_modified",
            "assignments_changed", "geometry_changed",
        ):
            self._regions_cache = None
            self._regions_cache_signature = None
            self._bbox_cache = None
            self._bbox_cache_signature = None
        for cb in self._listeners:
            try:
                cb(event)
            except Exception:  # noqa: BLE001
                pass

    # ------------------------------------------------------------------
    # High-level queries
    # ------------------------------------------------------------------
    def external_boundary(self) -> Optional[Boundary]:
        for b in self.boundaries:
            if b.btype == BoundaryType.EXTERNAL:
                return b
        return None

    def boundaries_of(self, btype: BoundaryType) -> list[Boundary]:
        return [b for b in self.boundaries if b.btype == btype]

    def material_by_id(self, mid: str) -> Optional[Material]:
        for m in self.materials:
            if m.id == mid:
                return m
        return None

    def bounding_box(self) -> tuple[float, float, float, float]:
        # v0.1.11 — cached for hot-loop callers (search/evaluator).
        # Invalidated by invalidate_regions_cache() on any boundary change.
        if (self._bbox_cache is not None
                and self._bbox_cache_signature == self._regions_cache_key()[0]):
            return self._bbox_cache
        if not self.boundaries:
            self._bbox_cache = (0.0, 0.0, 100.0, 50.0)
            self._bbox_cache_signature = self._regions_cache_key()[0]
            return self._bbox_cache
        xs, ys = [], []
        for b in self.boundaries:
            bx = b.bounding_box()
            xs.extend([bx[0], bx[2]])
            ys.extend([bx[1], bx[3]])
        self._bbox_cache = (min(xs), min(ys), max(xs), max(ys))
        self._bbox_cache_signature = self._regions_cache_key()[0]
        return self._bbox_cache

    # ------------------------------------------------------------------
    # Mutations (go through these so listeners get notified)
    # ------------------------------------------------------------------
    def add_boundary(self, b: Boundary) -> None:
        self.boundaries.append(b)
        self._notify("boundary_added")

    def remove_boundary(self, bid: str) -> None:
        self.boundaries = [b for b in self.boundaries if b.id != bid]
        self._notify("boundary_removed")

    def add_material(self, m: Material) -> None:
        if len(self.materials) >= self.settings.max_materials:
            raise RuntimeError("Maximum material count reached")
        self.materials.append(m)
        self._notify("material_added")

    def add_support(self, s: SupportInstance) -> None:
        self.supports.append(s)
        self._notify("support_added")

    def add_distributed_load(self, load: DistributedLoad) -> None:
        self.distributed_loads.append(load)
        self._notify("load_added")

    def add_line_load(self, load: LineLoad) -> None:
        self.line_loads.append(load)
        self._notify("load_added")

    # ------------------------------------------------------------------
    # v0.1.6 — Region / material resolution
    # ------------------------------------------------------------------
    def resolve_regions(self) -> list:
        """Compute the current material regions of the model.

        Regions are the faces of the planar graph formed by
        ``External ∪ MaterialBoundaries``. Water Table, Piezometric
        Lines, Tension Crack and Drawdown do NOT participate in the
        planar subdivision — they are overlays that only affect the
        slice-level pore-pressure computation.

        Each returned region is annotated with:
            - ``material_id`` — resolved via user click history (last
              winning assignment whose click-point still lies inside
              the region) or the first material of the project as a
              Slide-style default.
            - ``region_index`` — integer index in the returned list.

        Returns an empty list if there is no External or if shapely is
        not available.

        v0.1.11: results are cached and reused until any boundary or
        material assignment changes. The cache is invalidated by
        :meth:`invalidate_regions_cache`, which the project notifier
        calls automatically.
        """
        # v0.1.11 — fast path: return cached regions if still valid
        cache_key = self._regions_cache_key()
        if (self._regions_cache is not None
                and self._regions_cache_signature == cache_key):
            return self._regions_cache

        from ..geometry import build_regions
        external = self.external_boundary()
        if external is None:
            self._regions_cache = []
            self._regions_cache_signature = cache_key
            return self._regions_cache
        material_bs = self.boundaries_of(BoundaryType.MATERIAL)
        regions = build_regions(external, material_bs)
        # Default material = first in the project (Slide convention)
        default_mid = self.materials[0].id if self.materials else None
        # Resolve each region. Strategy (v0.1.14):
        #
        # Each region_assignment carries a polygon "footprint" — the
        # polygon of the region at the moment the user clicked. When a
        # new boundary subdivides a previously-assigned region, the new
        # sub-regions are still INSIDE the historical footprint, so
        # they should inherit the material.
        #
        # Algorithm (per region R):
        #   1. Direct hit — if any assignment click point lies inside R,
        #      use its material (last assignment wins).
        #   2. Footprint inheritance — for every assignment whose
        #      footprint polygon CONTAINS the region centroid,
        #      compute the intersection area between R and the
        #      footprint. The assignment with the largest intersection
        #      ratio wins. Most-recent assignment breaks ties.
        #   3. Otherwise, fall back to the default material.
        import math as _math

        # Pre-compute centroids and pre-build shapely Polygons (if
        # available) for fast geometric intersection. Pure-Python
        # fallback uses point-in-polygon and signed-area shoelace.
        try:
            from shapely.geometry import Polygon as _SPolygon
            _HAS_SHAPELY_HERE = True
        except ImportError:
            _HAS_SHAPELY_HERE = False

        def _polygon_intersection_area(verts_a, verts_b) -> float:
            """Intersection area of two convex/simple polygons.

            Uses shapely if available, falls back to a coarse
            point-sampling Monte-Carlo when shapely is missing.
            """
            if _HAS_SHAPELY_HERE:
                try:
                    pa = _SPolygon(verts_a)
                    pb = _SPolygon(verts_b)
                    if not pa.is_valid:
                        pa = pa.buffer(0)
                    if not pb.is_valid:
                        pb = pb.buffer(0)
                    return pa.intersection(pb).area
                except Exception:  # noqa: BLE001
                    return 0.0
            # Fallback: simple point-sampling approximation
            xs = [v[0] for v in verts_a]
            ys = [v[1] for v in verts_a]
            xmin, xmax = min(xs), max(xs)
            ymin, ymax = min(ys), max(ys)
            n_in = 0
            samples = 64
            for i in range(samples):
                for j in range(samples):
                    px = xmin + (xmax - xmin) * (i + 0.5) / samples
                    py = ymin + (ymax - ymin) * (j + 0.5) / samples
                    if (_point_in_polygon_verts(px, py, verts_a)
                            and _point_in_polygon_verts(px, py, verts_b)):
                        n_in += 1
            cell = ((xmax - xmin) * (ymax - ymin)) / (samples * samples)
            return n_in * cell

        for idx, region in enumerate(regions):
            region.region_index = idx
            region.material_id = default_mid

            # Step 1 — direct click hits. An assignment "click" point
            # that lies inside THIS region claims it. Last assignment
            # wins. Because regions are disjoint polygons, a point in
            # region 5 can never fall inside region 4 — so assigning a
            # material to one region never bleeds into a sibling.
            direct_hit = False
            for assignment in self.region_assignments:
                ax, ay = assignment["x"], assignment["y"]
                if _point_in_polygon_verts(ax, ay, region.polygon.vertices):
                    region.material_id = assignment.get("material_id")
                    direct_hit = True

            if direct_hit:
                continue  # resolved by a click that is physically inside

            # Step 2 — footprint inheritance for regions created by
            # subdividing a previously-painted region.
            #
            # The footprint captured at assignment time already encodes
            # the temporal logic:
            #   • If the user painted the ANCESTOR region and only later
            #     subdivided it, the stored footprint is the LARGE
            #     ancestor polygon → every child region lies inside it
            #     and correctly inherits.
            #   • If the user subdivided FIRST and then painted one
            #     CHILD, the stored footprint is that SMALL child
            #     polygon → it only contains the painted child, so
            #     siblings do NOT inherit.
            #
            # So the fix (v0.1.16) is: a region inherits an assignment's
            # material only if the region is essentially CONTAINED in the
            # footprint (the footprint is an ancestor of this region),
            # measured by "intersection area ≈ region area". This stops a
            # small child footprint from bleeding into a sibling while
            # still letting a large ancestor footprint feed all children.
            cx, cy = region.centroid()
            region_verts = tuple(
                (v.x, v.y) for v in region.polygon.vertices
            )
            region_area = region.area if hasattr(region, "area") else 0.0
            best_overlap = 0.0
            best_assignment = None
            for assignment in self.region_assignments:
                fp = assignment.get("footprint")
                if not fp:
                    continue
                if not _point_in_polygon_verts(cx, cy, [
                    Vertex(*p) for p in fp
                ]):
                    continue
                overlap = _polygon_intersection_area(region_verts, fp)
                # The footprint must essentially CONTAIN this region
                # (ancestor relationship). If the overlap is much smaller
                # than the region's own area, the footprint is a sibling
                # child, not an ancestor → skip it.
                if region_area > 0 and overlap < 0.95 * region_area:
                    continue
                if overlap >= best_overlap:
                    best_overlap = overlap
                    best_assignment = assignment
            if best_assignment is not None and best_overlap > 0:
                region.material_id = best_assignment.get("material_id")
        # Save to cache
        self._regions_cache = regions
        self._regions_cache_signature = cache_key
        return regions

    def _regions_cache_key(self):
        """Build a hashable signature of all data that affects
        ``resolve_regions()``. If any of these change, the cache is
        invalidated automatically.
        """
        boundary_sig = []
        for b in self.boundaries:
            if b.btype not in (BoundaryType.EXTERNAL, BoundaryType.MATERIAL):
                continue
            boundary_sig.append((
                b.btype.value,
                tuple((round(v.x, 6), round(v.y, 6))
                      for v in b.polyline.vertices),
            ))
        boundary_sig = tuple(boundary_sig)
        assign_sig = tuple(
            (round(a["x"], 6), round(a["y"], 6), a.get("material_id"),
             tuple((round(p[0], 6), round(p[1], 6))
                   for p in a.get("footprint", ())))
            for a in self.region_assignments
        )
        mat_sig = tuple(m.id for m in self.materials) if self.materials else ()
        return (boundary_sig, assign_sig, mat_sig)

    def invalidate_regions_cache(self) -> None:
        """Force the regions cache to be recomputed on the next call."""
        self._regions_cache = None
        self._regions_cache_signature = None
        self._bbox_cache = None
        self._bbox_cache_signature = None

    def material_at(self, x: float, y: float):
        """Return the resolved ``Material`` at (x, y), or None."""
        regions = self.resolve_regions()
        return self._material_in(regions, x, y)

    def materials_at(self, points) -> list:
        """Resolve several points against ONE lookup of the regions.

        v0.1.63 — ``resolve_regions`` validates its cache by rebuilding a
        signature over every vertex of every external and material
        boundary, which costs more than the point-in-polygon scan it
        guards. That was invisible while callers asked for one point at a
        time; the slicer now asks once per band of a slice column, and
        paying the signature per band made slicing measurably slower.
        Callers with several points should use this instead.
        """
        regions = self.resolve_regions()
        return [self._material_in(regions, x, y) for x, y in points]

    def _material_in(self, regions, x: float, y: float):
        for r in regions:
            if _point_in_polygon_verts(x, y, r.polygon.vertices):
                mid = getattr(r, "material_id", None)
                if mid is None:
                    return self.materials[0] if self.materials else None
                return self.material_by_id(mid)
        return None

    def assign_material_at(self, x: float, y: float, material_id: str) -> bool:
        """Record a user "paint" click at (x, y) with the given material.

        v0.1.14 — also captures a **polygon footprint** of the region
        that was clicked, so subsequent subdivisions (caused by new
        Material Boundaries) inherit the material from the right
        ancestor region instead of falling back to euclidean nearest
        neighbour, which can pick the wrong layer when clicks are far
        apart but in the same layer.

        Returns True if the click lies inside any region.
        """
        regions = self.resolve_regions()
        target = None
        for r in regions:
            if _point_in_polygon_verts(x, y, r.polygon.vertices):
                target = r
                break
        if target is None:
            return False

        # Capture the region polygon at assignment time
        footprint = tuple((v.x, v.y) for v in target.polygon.vertices)

        # Upsert: overwrite the most recent assignment at this exact
        # click point, or append if none exists
        for a in self.region_assignments:
            if abs(a["x"] - x) < 1e-6 and abs(a["y"] - y) < 1e-6:
                a["material_id"] = material_id
                a["footprint"] = footprint
                self.is_dirty = True
                self._notify("assignments_changed")
                return True
        self.region_assignments.append({
            "x": x, "y": y,
            "material_id": material_id,
            "footprint": footprint,
        })
        self.is_dirty = True
        self._notify("assignments_changed")
        return True

    def prune_stale_assignments(self) -> int:
        """Remove click records that no longer lie in any region.

        Called after boundary edits so saved files don't accumulate
        garbage. Returns the number of stale entries pruned.
        """
        regions = self.resolve_regions()
        if not regions:
            # Nothing to compare against — keep everything so that
            # assignments survive temporary geometry-loss states.
            return 0
        kept = []
        pruned = 0
        for a in self.region_assignments:
            if any(_point_in_polygon_verts(a["x"], a["y"], r.polygon.vertices)
                   for r in regions):
                kept.append(a)
            else:
                pruned += 1
        if pruned:
            self.region_assignments = kept
            self._notify("assignments_changed")
        return pruned
    def to_dict(self) -> dict:
        return {
            "format_version": FILE_FORMAT_VERSION,
            "id": self.id,
            "name": self.name,
            "settings": self.settings.to_dict(),
            "boundaries": [b.to_dict() for b in self.boundaries],
            "materials": [m.to_dict() for m in self.materials],
            "supports": [s.to_dict() for s in self.supports],
            "support_types": [t.to_dict() for t in self.support_types],
            "distributed_loads": [l.to_dict() for l in self.distributed_loads],
            "line_loads": [l.to_dict() for l in self.line_loads],
            "seismic": self.seismic.to_dict(),
            # v0.1.6
            "region_assignments": list(self.region_assignments),
            # v0.1.7
            "tension_crack_properties": self.tension_crack_properties.to_dict(),
            # v0.1.23
            "water_pressure_grid": (
                self.water_pressure_grid.to_dict()
                if self.water_pressure_grid is not None else None
            ),
            # v0.1.25
            "fem_mesh": (self.fem_mesh.to_dict()
                         if self.fem_mesh is not None else None),
            "seepage_bcs": (self.seepage_bcs.to_dict()
                            if self.seepage_bcs is not None else None),
            "random_variables": [rv.to_dict()
                                 for rv in self.random_variables],
            "annotations": self.annotations.to_list(),
            "focus_objects": [f.to_dict() for f in self.focus_objects],
        }

    def save(self, path: Optional[Path] = None) -> Path:
        path = Path(path) if path else self.file_path
        if path is None:
            raise ValueError("No path specified and project has never been saved")
        path.write_text(
            json.dumps(self.to_dict(), indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        self.file_path = path
        self.results_path = path.with_suffix(".h5")
        self.is_dirty = False
        self._notify("saved")
        return path

    @classmethod
    def load(cls, path: Path | str) -> "Project":
        path = Path(path)
        data = json.loads(path.read_text(encoding="utf-8"))
        return cls.from_dict(data, path)

    @classmethod
    def from_dict(cls, data: dict, path: Optional[Path] = None) -> "Project":
        proj = cls(name=data.get("name", "Untitled"))
        proj.id = data.get("id", proj.id)
        proj.settings = ProjectSettings.from_dict(data.get("settings", {}))
        proj.boundaries = [Boundary.from_dict(b) for b in data.get("boundaries", [])]
        proj.materials = [Material.from_dict(m) for m in data.get("materials", [])]

        # v0.1.62 — B̄ migration. Before this version the rapid-drawdown
        # B-bar model read ``b_bar`` off the material with getattr and fell
        # back to 1.0, so EVERY material behaved undrained with full
        # transfer. The field now defaults to "freely draining" per the
        # reference, which would silently lower the pore pressures — and
        # therefore change the factor of safety — of a project saved
        # earlier. Files written before the keys existed are given back
        # the old implicit values, exactly as v0.1.60 did for
        # ``use_sat_unit_weight``. Only projects created from v0.1.62 on
        # start from the new default.
        _mats_raw = data.get("materials", [])
        _has_new_keys = any(
            ("b_bar" in m or "undrained_behaviour" in m) for m in _mats_raw
        )
        if (proj.settings.groundwater.rapid_drawdown
                and _mats_raw and not _has_new_keys):
            for m in proj.materials:
                m.undrained_behaviour = True
                m.b_bar = 1.0

        from ..support import SupportInstance as _SI
        proj.supports = [_SI.from_dict(s) for s in data.get("supports", [])]
        # v0.1.14 — support type definitions
        from ..support import support_from_dict as _stfd
        proj.support_types = [
            _stfd(t) for t in data.get("support_types", [])
        ]

        proj.distributed_loads = [
            DistributedLoad.from_dict(d) for d in data.get("distributed_loads", [])
        ]
        proj.line_loads = [LineLoad.from_dict(l) for l in data.get("line_loads", [])]
        proj.seismic = SeismicLoad.from_dict(data.get("seismic", {}))
        # v0.1.6
        proj.region_assignments = list(data.get("region_assignments", []))
        # v0.1.14 — normalise footprints to tuple-of-tuples (JSON parses
        # them as lists, but our cache key needs hashable values)
        for a in proj.region_assignments:
            fp = a.get("footprint")
            if fp is not None:
                a["footprint"] = tuple((float(p[0]), float(p[1])) for p in fp)
        # v0.1.7
        from ..geometry.tension_crack import TensionCrackProperties
        if "tension_crack_properties" in data:
            proj.tension_crack_properties = TensionCrackProperties.from_dict(
                data["tension_crack_properties"]
            )

        # v0.1.23 — Water Pressure Grid
        wpg = data.get("water_pressure_grid")
        if wpg:
            from ..hydraulic.water_pressure_grid import WaterPressureGrid
            proj.water_pressure_grid = WaterPressureGrid.from_dict(wpg)

        # v0.1.25 — FE mesh
        fm = data.get("fem_mesh")
        if fm:
            from ogr_fem2d.mesh import Mesh as _Mesh
            proj.fem_mesh = _Mesh.from_dict(fm)
        fos = data.get("focus_objects")
        if fos:
            from ogr_slip2d.focus import FocusObject as _FO
            proj.focus_objects = [_FO.from_dict(d) for d in fos]

        ann = data.get("annotations")
        if ann:
            from ..annotations import AnnotationLayer as _AL
            proj.annotations = _AL.from_list(ann)

        rvs = data.get("random_variables")
        if rvs:
            from ..statistics import RandomVariable as _RV
            proj.random_variables = [_RV.from_dict(d) for d in rvs]

        sb = data.get("seepage_bcs")
        if sb:
            from ogr_fem2d.solvers import SeepageBoundaryConditions as _SBC
            proj.seepage_bcs = _SBC.from_dict(sb)

        if path:
            proj.file_path = path
            proj.results_path = path.with_suffix(".h5")
        proj.is_dirty = False
        return proj


# ----------------------------------------------------------------------
# Utilities
# ----------------------------------------------------------------------
def _point_in_polygon_verts(x: float, y: float, verts) -> bool:
    """Ray-casting point-in-polygon against a list of Vertex-like objects."""
    n = len(verts)
    if n < 3:
        return False
    inside = False
    j = n - 1
    for i in range(n):
        xi, yi = verts[i].x, verts[i].y
        xj, yj = verts[j].x, verts[j].y
        if ((yi > y) != (yj > y)) and (
            x < (xj - xi) * (y - yi) / (yj - yi + 1e-20) + xi
        ):
            inside = not inside
        j = i
    return inside
