# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Samuel Sáez López — Universidad Politécnica de Cartagena
"""
Tests for v0.1.232 — the Block Search Polyline exists, and every Block
Search object says which of the four it is. Defect D109.

**The invariant**: a Block Search object gives each trial surface exactly
what the reference says its kind gives. A Window, a Line and a Point give
ONE vertex (at random inside, at random along, and the point itself); a
Polyline gives TWO points along it AND the stretch of polyline between
them — «The slip surface will then be constrained to follow the polyline,
BETWEEN the two points». How each of its two points is generated is chosen
per side: anywhere along the polyline, anywhere on its end segment, or at
its end vertex.

**What was wrong.** OGR inferred the kind from the vertex count on every
trial surface and took ONE point from every object, so the Polyline did
not exist: a surface could touch a weak layer at one point and never run
along it. Verification problem 75 publishes a flat of 80.4 m on the top of
its till, and the Block Search could not reach it by construction (its
archived critical surfaces have three vertices). The kind is now stored
on the object (``Boundary.block_object``), because a two-vertex Line and a
two-vertex Polyline cannot be told apart by their vertices.

**External anchor (rule 1): Tutorial 03 of the reference's own manual**
(Non-Circular Surfaces). It runs on the model of Tutorial 02 (Materials &
Loading), whose text gives every coordinate, material and load; the
tutorial adds a one-segment polyline (39, 23)-(81, 31) inside the weak
layer, both points «Any Line Segment», projection angles fixed at 135° and
45°, 5000 surfaces. Two published statements are checked:

* «all slip surfaces generated by the search, will consist of three line
  segments - a line segment along the Block Search Polyline, and the left
  and right projected segments» — an identity, on every generated surface;
* «The Global Minimum safety factor for a Bishop analysis is 0.762» —
  within 3 %, with 300 surfaces. OGR finds 0.755177 with 300 and 0.747654
  with 5000 (measured in v0.1.232 with the project's seed): BELOW the
  published minimum, as a search that happened to sample the family more
  finely would. With the angles fixed the family has two dimensions, the
  two points along the segment, so both searches sample the same set of
  surfaces with different random numbers; the 3 % is the room that needs.
  Nothing was tuned towards 0.762. The slice count is OGR's default (25);
  the tutorial does not state the reference's.

**Identities**:

* Polyline population: the vertices between the two projected ends lie on
  the polyline, and every vertex of the polyline strictly between the
  first and the last of them is present.
* End Point puts that side's point ON the end vertex for every surface;
  Line Segment keeps it on the end segment.
* An object saved before v0.1.232 stores no kind. Two open vertices without
  a kind are a LINE and give exactly the trial surfaces of an object
  declared a Line, bit for bit — which is what keeps every model of the
  verification bank on its digits.

**Rule 7**: the same two vertices declared Line and Polyline give 1.997758
and 0.755177 (measured); each point option moves the minimum too.

COST. The anchor model is small; seven Block Searches of 300 surfaces and a
handful of rule checks, about 25 s. One MainWindow for the interface
checks.
"""
from __future__ import annotations

import math
import os

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

try:
    from PySide6.QtWidgets import QApplication
    _QT = True
except ImportError:  # pragma: no cover
    _QT = False


def _requires_qt(cls):
    return cls if _QT else type(cls.__name__, (), {})

#: Tutorial 03: «The Global Minimum safety factor for a Bishop analysis is
#: 0.762» (5000 surfaces, angles 135 / 45).
_PUBLISHED_BISHOP = 0.762
_N = 300
_CACHE: dict = {}
_WINDOWS: list = []


# ----------------------------------------------------------------------
def _tutorial(kind=None, left=None, right=None, polyline=None, n=_N):
    """The model of Tutorial 02, with the Block Search of Tutorial 03.

    Every number is the tutorial's: the External boundary, the two material
    boundaries that bound the weak layer, the water table (assigned to both
    materials, Hu = 1, hydrostatic), the 50 kN/m2 load on the crest, the two
    materials, and the polyline. ``kind`` None leaves the object without a
    stored kind, the way a file saved before v0.1.232 reads — and imports
    nothing this version added, so the tests that use it discriminate the
    old tree by behaviour and not by a missing name.
    """
    from ogr_core.geometry import Boundary, BoundaryType, Polyline, Vertex
    from ogr_core.loads import DistributedLoad, LoadDistribution
    from ogr_core.materials import Material, PorePressureType
    from ogr_core.materials.builtin_models import MohrCoulomb
    from ogr_core.project import Project

    p = Project("Tutorial 02/03")
    ext = Polyline(vertices=[Vertex(*v) for v in (
        (5, 0), (100, 0), (100, 34), (100, 36), (100, 40), (67, 40),
        (43, 28), (5, 28), (5, 18), (5, 16))], closed=True)
    ext.ensure_ccw()
    p.add_boundary(Boundary(polyline=ext, btype=BoundaryType.EXTERNAL))
    for a, b in (((5, 18), (100, 36)), ((5, 16), (100, 34))):
        p.add_boundary(Boundary(polyline=Polyline(
            vertices=[Vertex(*a), Vertex(*b)], closed=False),
            btype=BoundaryType.MATERIAL))
    wt = Boundary(polyline=Polyline(vertices=[Vertex(*v) for v in (
        (5, 28), (43, 28), (49, 30), (60, 34), (66, 36), (74, 38),
        (80, 38.5), (100, 38.5))], closed=False),
        btype=BoundaryType.WATER_TABLE)
    p.add_boundary(wt)
    soil = Material(name="soil 1", unit_weight=19.0,
                    strength=MohrCoulomb(cohesion=28.5, friction_angle=20.0),
                    pore_pressure=PorePressureType.WATER_TABLE,
                    water_surface_id=wt.id)
    weak = Material(name="weak layer", unit_weight=18.5,
                    strength=MohrCoulomb(cohesion=0.0, friction_angle=10.0),
                    pore_pressure=PorePressureType.WATER_TABLE,
                    water_surface_id=wt.id)
    p.materials = [soil, weak]
    p.resolve_regions()
    p.assign_material_at(50.0, 10.0, soil.id)
    p.assign_material_at(50.0, _layer_mid(50.0), weak.id)
    p.assign_material_at(50.0, 29.0, soil.id)
    p.add_distributed_load(DistributedLoad(
        start=Vertex(70.0, 40.0), end=Vertex(80.0, 40.0), magnitude_1=50.0,
        distribution=LoadDistribution.CONSTANT))
    pts = polyline or ((39.0, 23.0), (81.0, 31.0))
    obj = Boundary(polyline=Polyline(vertices=[Vertex(*v) for v in pts],
                                     closed=False),
                   btype=BoundaryType.BLOCK_SEARCH_OBJECT)
    if kind is not None:
        from ogr_core.geometry import BlockObjectSpec
        spec = BlockObjectSpec(kind=kind)
        if left is not None:
            spec.left_point = left
        if right is not None:
            spec.right_point = right
        obj.block_object = spec
    p.add_boundary(obj)
    s = p.settings.search
    s.surface_type = "non_circular"
    s.search_method = "block"
    s.block_num_surfaces = n
    s.block_left_start_angle_deg = s.block_left_end_angle_deg = 135.0
    s.block_right_start_angle_deg = s.block_right_end_angle_deg = 45.0
    return p


def _layer_mid(x: float) -> float:
    """The middle of the weak layer at ``x`` (between (5,16)-(100,34) and
    (5,18)-(100,36))."""
    return 17.0 + (x - 5.0) * 18.0 / 95.0


def _run(key, **kw):
    """A Bishop Block Search on the tutorial model, cached by ``key``."""
    if key not in _CACHE:
        from ogr_slip2d.analysis_runner import build_search
        p = _tutorial(**kw)
        _CACHE[key] = (p, build_search(p, "bishop_simplified").run(p))
    return _CACHE[key]


def _polyline_run():
    from ogr_core.geometry import BlockObjectKind
    return _run("polyline", kind=BlockObjectKind.POLYLINE)


def _dist_to_polyline(x, y, pts) -> float:
    best = float("inf")
    for (ax, ay), (bx, by) in zip(pts, pts[1:]):
        dx, dy = bx - ax, by - ay
        t = max(0.0, min(1.0, ((x - ax) * dx + (y - ay) * dy)
                         / (dx * dx + dy * dy)))
        best = min(best, math.hypot(x - ax - t * dx, y - ay - t * dy))
    return best


# ======================================================================
class TestTheTutorialPublishesWhatThePolylineGives:
    """Rule 1, against the reference's own tutorial."""

    def test_every_surface_has_three_segments(self):
        """«all slip surfaces generated by the search, will consist of
        three line segments»."""
        _p, r = _polyline_run()
        counts = {len(e.surface.polyline.vertices) for e in r.evaluations}
        assert counts == {4}, sorted(counts)

    def test_the_bishop_minimum_is_the_published_one(self):
        _p, r = _polyline_run()
        fos = r.critical.fos
        assert abs(fos / _PUBLISHED_BISHOP - 1.0) < 0.03, fos

    def test_three_open_vertices_are_a_polyline_without_a_kind(self):
        """A file needs no new key for this: an open object of more than two
        vertices is read as a Polyline. The tutorial's polyline with a
        collinear midpoint, (60, 27), is the same line, so it reaches the
        same minimum. Before v0.1.232 it gave ONE point somewhere along it,
        the surface could not run along the layer, and the minimum was
        near 2 — which is why this check needs no name this version added.
        """
        _p, r = _run("inferred",
                     polyline=((39.0, 23.0), (60.0, 27.0), (81.0, 31.0)))
        assert abs(r.critical.fos / _PUBLISHED_BISHOP - 1.0) < 0.03, \
            r.critical.fos

    def test_the_middle_segment_runs_inside_the_weak_layer(self):
        """The whole point of the object: the surface travels ALONG the
        layer, not through it at one point."""
        _p, r = _polyline_run()
        v = r.critical.surface.polyline.vertices
        for q in (v[1], v[2]):
            lo = 16.0 + (q.x - 5.0) * 18.0 / 95.0
            assert lo - 1e-9 <= q.y <= lo + 2.0 + 1e-9, (q.x, q.y)
        assert v[2].x - v[1].x > 10.0, (v[1].x, v[2].x)


class TestWhatEachKindGives:
    """The four definitions, as identities on the generated population."""

    def test_the_polyline_gives_its_stretch(self):
        """A three-segment polyline along the layer: the vertices between
        the two projected ends lie ON it, and every polyline vertex between
        the first and the last of them is present."""
        from ogr_core.geometry import BlockObjectKind
        pts = ((39.0, _layer_mid(39.0)), (55.0, _layer_mid(55.0) - 0.4),
               (68.0, _layer_mid(68.0) + 0.4), (81.0, _layer_mid(81.0)))
        _p, r = _run("three_segments", kind=BlockObjectKind.POLYLINE,
                     polyline=pts)
        assert r.evaluations, "no surface was generated"
        scale = 100.0
        for e in r.evaluations:
            inner = e.surface.polyline.vertices[1:-1]
            for q in inner:
                assert _dist_to_polyline(q.x, q.y, pts) < 1e-9 * scale, \
                    (q.x, q.y)
            xs = [q.x for q in inner]
            for vx, vy in pts:
                if xs[0] + 1e-3 < vx < xs[-1] - 1e-3:
                    assert any(abs(q.x - vx) < 1e-9 and abs(q.y - vy) < 1e-9
                               for q in inner), (vx, [(q.x, q.y)
                                                      for q in inner])

    def test_a_line_gives_one_vertex(self):
        from ogr_core.geometry import BlockObjectKind
        _p, r = _run("line", kind=BlockObjectKind.LINE)
        assert {len(e.surface.polyline.vertices)
                for e in r.evaluations} == {3}

    def test_end_point_is_the_end_vertex_on_every_surface(self):
        from ogr_core.geometry import BlockObjectKind, PolylinePointMode
        _p, r = _run("end_any", kind=BlockObjectKind.POLYLINE,
                     left=PolylinePointMode.END_POINT)
        assert r.evaluations
        for e in r.evaluations:
            q = e.surface.polyline.vertices[1]
            assert (q.x, q.y) == (39.0, 23.0), (q.x, q.y)

    def test_segment_keeps_the_point_on_the_end_segment(self):
        """On the three-segment polyline, «Left Line Segment» draws the
        left point on the FIRST segment only."""
        from ogr_core.geometry import BlockObjectKind, PolylinePointMode
        pts = ((39.0, _layer_mid(39.0)), (55.0, _layer_mid(55.0)),
               (68.0, _layer_mid(68.0)), (81.0, _layer_mid(81.0)))
        _p, r = _run("segment_left", kind=BlockObjectKind.POLYLINE,
                     left=PolylinePointMode.SEGMENT,
                     right=PolylinePointMode.END_POINT, polyline=pts)
        assert r.evaluations
        firsts = [e.surface.polyline.vertices[1].x for e in r.evaluations]
        assert all(39.0 <= x <= 55.0 + 1e-9 for x in firsts), \
            (min(firsts), max(firsts))
        assert max(firsts) - min(firsts) > 10.0, "not spread over it"


class TestTheKindIsStoredAndOldFilesKeepTheirDigits:

    def test_the_inference_for_a_file_without_kind(self):
        from ogr_core.geometry import BlockObjectKind, Polyline, Vertex
        from ogr_core.geometry.block_object import infer_block_kind
        v = [Vertex(0, 0), Vertex(1, 0), Vertex(2, 1), Vertex(3, 1)]
        assert infer_block_kind(Polyline(vertices=v[:1])) is \
            BlockObjectKind.POINT
        assert infer_block_kind(Polyline(vertices=v[:2])) is \
            BlockObjectKind.LINE
        assert infer_block_kind(Polyline(vertices=v[:2], closed=True)) is \
            BlockObjectKind.LINE
        assert infer_block_kind(Polyline(vertices=v, closed=True)) is \
            BlockObjectKind.WINDOW
        assert infer_block_kind(Polyline(vertices=v[:3])) is \
            BlockObjectKind.POLYLINE
        assert infer_block_kind(Polyline(vertices=[])) is None

    def test_two_vertices_without_kind_are_the_line_bit_for_bit(self):
        """What keeps the bank's six block models on their digits: they
        all declare open two-vertex objects and no kind."""
        from ogr_core.geometry import BlockObjectKind
        _p, legacy = _run("legacy")
        _p, line = _run("line", kind=BlockObjectKind.LINE)
        assert [e.fos for e in legacy.evaluations] == \
            [e.fos for e in line.evaluations]
        assert [[(v.x, v.y) for v in e.surface.polyline.vertices]
                for e in legacy.evaluations] == \
            [[(v.x, v.y) for v in e.surface.polyline.vertices]
             for e in line.evaluations]

    def test_the_kind_survives_the_file(self):
        from ogr_core.geometry import (BlockObjectKind, BoundaryType,
                                       PolylinePointMode)
        from ogr_core.project import Project
        p = _tutorial(kind=BlockObjectKind.POLYLINE,
                      left=PolylinePointMode.SEGMENT,
                      right=PolylinePointMode.END_POINT,
                      polyline=((39.0, 23.0), (60.0, 27.0), (81.0, 31.0)))
        back = Project.from_dict(p.to_dict())
        obj = next(b for b in back.boundaries
                   if b.btype == BoundaryType.BLOCK_SEARCH_OBJECT)
        assert obj.block_object.kind is BlockObjectKind.POLYLINE
        assert obj.block_object.left_point is PolylinePointMode.SEGMENT
        assert obj.block_object.right_point is PolylinePointMode.END_POINT

    def test_an_object_without_kind_writes_the_file_it_always_wrote(self):
        from ogr_core.geometry import BoundaryType
        p = _tutorial()
        for b in p.boundaries:
            d = b.to_dict()
            assert "block_object" not in d, b.btype
        assert any(b.btype == BoundaryType.BLOCK_SEARCH_OBJECT
                   for b in p.boundaries)

    def test_only_the_block_object_carries_it(self):
        """``convert_boundary`` drops the kind on the way out, and an object
        made by conversion is read with the inferred kind."""
        from ogr_core.geometry import (BlockObjectKind, BlockObjectSpec,
                                       Boundary, BoundaryType, Polyline,
                                       Vertex, convert_boundary)
        b = Boundary(polyline=Polyline(vertices=[Vertex(0, 0), Vertex(1, 1)]),
                     btype=BoundaryType.BLOCK_SEARCH_OBJECT,
                     block_object=BlockObjectSpec(BlockObjectKind.POLYLINE))
        wt = convert_boundary(b, BoundaryType.WATER_TABLE)
        assert wt.block_object is None
        assert "block_object" not in wt.to_dict()
        back = convert_boundary(wt, BoundaryType.BLOCK_SEARCH_OBJECT)
        assert back.block_object is None


class TestEveryOptionMovesTheNumber:
    """Rule 7."""

    def test_line_against_polyline(self):
        from ogr_core.geometry import BlockObjectKind
        _p, line = _run("line", kind=BlockObjectKind.LINE)
        _p, poly = _polyline_run()
        assert line.critical.fos > poly.critical.fos * 1.5, \
            (line.critical.fos, poly.critical.fos)

    def test_each_point_option(self):
        from ogr_core.geometry import BlockObjectKind, PolylinePointMode as M
        _p, anyany = _polyline_run()
        _p, endany = _run("end_any", kind=BlockObjectKind.POLYLINE,
                          left=M.END_POINT)
        _p, anyend = _run("any_end", kind=BlockObjectKind.POLYLINE,
                          right=M.END_POINT)
        mins = [round(r.critical.fos, 9) for r in (anyany, endany, anyend)]
        assert len(set(mins)) == 3, mins


class TestTheRulesTheReferenceStates:

    def _obj(self, pts, kind=None, closed=False, left=None):
        from ogr_core.geometry import (BlockObjectSpec, Boundary,
                                       BoundaryType, Polyline, Vertex)
        b = Boundary(polyline=Polyline(vertices=[Vertex(*v) for v in pts],
                                       closed=closed),
                     btype=BoundaryType.BLOCK_SEARCH_OBJECT)
        if kind is not None:
            b.block_object = BlockObjectSpec(kind)
            if left is not None:
                b.block_object.left_point = left
        return b

    def test_the_kind_has_to_fit_the_geometry(self):
        from ogr_core.geometry import BlockObjectKind as K
        from ogr_core.project.rules import block_object_refusal
        assert block_object_refusal(
            self._obj([(0, 0), (1, 1)], K.POINT)).code == \
            "block_object_geometry"
        assert block_object_refusal(
            self._obj([(0, 0), (1, 1), (2, 1)], K.LINE)).code == \
            "block_object_geometry"
        assert block_object_refusal(
            self._obj([(0, 0), (1, 1)], K.WINDOW)).code == \
            "block_object_geometry"
        assert block_object_refusal(
            self._obj([(0, 0), (1, 1), (0, 1)], K.POLYLINE,
                      closed=True)).code == "block_object_geometry"
        assert block_object_refusal(self._obj([(0, 0), (1, 1)],
                                              K.POLYLINE)) is None

    def test_a_polyline_has_to_advance_in_x(self):
        from ogr_core.geometry import BlockObjectKind as K
        from ogr_core.project.rules import block_object_refusal
        why = block_object_refusal(self._obj([(0, 0), (5, 1), (3, 2)],
                                             K.POLYLINE))
        assert why.code == "block_polyline_not_monotone"
        # drawn from right to left is still a polyline that advances
        assert block_object_refusal(self._obj([(5, 0), (3, 1), (0, 2)],
                                              K.POLYLINE)) is None

    def test_line_segment_needs_two_segments(self):
        from ogr_core.geometry import BlockObjectKind as K, PolylinePointMode
        from ogr_core.project.rules import block_object_refusal
        why = block_object_refusal(self._obj(
            [(0, 0), (5, 1)], K.POLYLINE, left=PolylinePointMode.SEGMENT))
        assert why.code == "block_polyline_segment_mode"

    def test_nothing_may_overlap_a_polyline(self):
        from ogr_core.geometry import BlockObjectKind as K
        from ogr_core.project.rules import block_objects_refusal
        p = _tutorial(kind=K.POLYLINE)
        assert block_objects_refusal(p) is None
        p.add_boundary(self._obj([(60.0, 20.0), (62.0, 22.0)], K.LINE))
        why = block_objects_refusal(p)
        assert why is not None and why.code == "block_polyline_overlap"

    def test_touching_at_an_end_is_allowed(self):
        from ogr_core.geometry import BlockObjectKind as K
        from ogr_core.project.rules import block_objects_refusal
        p = _tutorial(kind=K.POLYLINE)
        p.add_boundary(self._obj([(81.0, 31.0)], K.POINT))
        assert block_objects_refusal(p) is None

    def test_the_analysis_refuses_it(self):
        from ogr_core.geometry import BlockObjectKind as K
        from ogr_slip2d.analysis_runner import check_analysis_settings
        p = _tutorial(kind=K.POLYLINE)
        assert check_analysis_settings(p) == []
        p.add_boundary(self._obj([(60.0, 20.0), (62.0, 22.0)], K.LINE))
        problems = check_analysis_settings(p)
        assert any("lateral extent" in m for m in problems), problems


class TestTheNoteNoLongerSaysOneVertex:
    """The note of v0.1.156 said every trial surface takes ONE vertex from
    each object, which the Polyline made false. It keeps everything the
    tests of v0.1.156 and the bank read."""

    def test_the_wording(self):
        from ogr_core.geometry import BlockObjectKind
        from ogr_slip2d.analysis_runner import _block_group_notes
        notes = _block_group_notes(_tutorial(kind=BlockObjectKind.POLYLINE))
        assert len(notes) == 1, notes
        assert "one vertex" not in notes[0], notes[0]
        assert "1 Block Search object" in notes[0], notes[0]
        # v0.1.233 (D100) — the count is called «Implicit Region Bands» now:
        # «Number of Groups» was the reference's name for Multiple Groups,
        # which it is not. Changed on purpose; the note says the same.
        assert "Implicit Region Bands" in notes[0], notes[0]
        assert not ("stable" in notes[0] and "head" in notes[0])
        assert "edge of the search grid" not in notes[0]
        assert "path_optimize" not in notes[0]


class TestTheOperations:
    """The API takes the kind, shows it and refuses what the rule refuses."""

    def _pid(self, ws):
        from ogr_api import call
        pid = call(ws, "project_new", name="D109")["project_id"]
        call(ws, "model_define", project_id=pid, spec={
            "external": [[0, 0], [100, 0], [100, 30], [60, 30], [40, 20],
                         [0, 20]],
            "materials": [{"name": "Soil", "unit_weight": 20.0, "strength": {
                "model": "mohr_coulomb",
                "params": {"cohesion": 5.0, "friction_angle": 30.0}}}],
            "settings": {"search.surface_type": "non_circular",
                         "search.search_method": "block"}})
        return pid

    def test_add_edit_and_show(self):
        from ogr_api import Workspace, call
        ws = Workspace()
        pid = self._pid(ws)
        out = call(ws, "boundary_add", project_id=pid,
                   type="block_search_object", points=[[30, 10], [70, 12]],
                   block_object={"kind": "polyline", "left_point": "any",
                                 "right_point": "end_point"})
        info = out["boundary"]["block_object"]
        assert info == {"kind": "polyline", "left_point": "any",
                        "right_point": "end_point", "stored": True}, info
        bid = out["boundary"]["id"]
        out = call(ws, "boundary_edit", project_id=pid, boundary=bid,
                   op="block_object", block_object=None)
        assert out["boundary"]["block_object"] == {"kind": "line",
                                                   "stored": False}

    def test_the_rule_refuses_through_the_api(self):
        from ogr_api import Workspace, call
        from ogr_api.errors import InvalidArgument
        ws = Workspace()
        pid = self._pid(ws)
        try:
            call(ws, "boundary_add", project_id=pid,
                 type="block_search_object",
                 points=[[30, 10], [70, 12], [50, 14]],
                 block_object="polyline")
        except InvalidArgument as exc:
            assert "advance in x" in str(exc), str(exc)
        else:
            raise AssertionError("a polyline that doubles back was added")

    def test_the_catalog_lists_the_kinds(self):
        from ogr_api.catalog import catalog
        entry = next(e for e in catalog("boundary_types")
                     if e["id"] == "block_search_object")
        assert entry["block_object"]["kinds"] == [
            "window", "line", "point", "polyline"]
        assert entry["block_object"]["polyline_point_modes"] == [
            "any", "segment", "end_point"]


# ======================================================================
def _window():
    if _WINDOWS:
        return _WINDOWS[0]
    from ogr_gui.i18n import set_language
    from ogr_gui.main_window import MainWindow
    QApplication.instance() or QApplication([])
    set_language("en")
    w = MainWindow()
    _WINDOWS.append(w)
    return w


def _menu_texts(w, title):
    from ogr_gui.i18n import tr
    for a in w.menuBar().actions():
        if a.text().replace("&", "") == tr(title):
            return [x.text() for x in a.menu().actions()]
    return []


@_requires_qt
class TestTheInterfaceDrawsAllFour:

    def test_the_four_actions_are_in_the_surfaces_menu(self):
        """Rule 3: reachable from the menu bar, under the reference's names."""
        w = _window()
        texts = _menu_texts(w, "Surfaces")
        for key in ("block_object", "block_line", "block_point",
                    "block_polyline"):
            assert w._actions[key].text() in texts, key
        assert w._actions["block_object"].text() == "Add Block Search Window"

    def test_each_mode_stores_its_kind(self):
        from ogr_core.geometry import BlockObjectKind, BoundaryType
        from ogr_gui.canvas.tool_mode import ToolMode
        w = _window()
        before = len(w.project.boundaries)
        previous = w.project.settings.search.search_method
        try:
            w.project.settings.search.search_method = "block"
            w.canvas.set_tool_mode(ToolMode.DRAW_BLOCK_POINT)
            w.canvas.add_manual_point(10.0, 5.0)        # one click finishes
            w.canvas.set_tool_mode(ToolMode.DRAW_BLOCK_LINE)
            w.canvas.add_manual_point(10.0, 5.0)
            w.canvas.add_manual_point(20.0, 6.0)        # two clicks finish
            w.canvas.set_tool_mode(ToolMode.DRAW_BLOCK_POLYLINE)
            for x, y in ((10.0, 5.0), (20.0, 6.0), (30.0, 6.5)):
                w.canvas.add_manual_point(x, y)
            w.canvas._finish_drawing()
            added = w.project.boundaries[before:]
            assert [b.btype for b in added] == \
                [BoundaryType.BLOCK_SEARCH_OBJECT] * 3
            assert [b.block_object.kind for b in added] == [
                BlockObjectKind.POINT, BlockObjectKind.LINE,
                BlockObjectKind.POLYLINE]
            assert [len(b.polyline.vertices) for b in added] == [1, 2, 3]
            # The Polyline opened its options, not modal.
            dlg = w._block_object_dialog
            assert dlg is not None and not dlg.isModal()
        finally:
            dlg = getattr(w, "_block_object_dialog", None)
            if dlg is not None:
                dlg.close()
            while len(w.project.boundaries) > before:
                w.project.boundaries.pop()
            w.project.settings.search.search_method = previous
            w.canvas.set_tool_mode(ToolMode.SELECT)

    def test_the_dialog_sets_the_point_options_undoably(self):
        from ogr_core.geometry import (BlockObjectKind, BlockObjectSpec,
                                       Boundary, BoundaryType,
                                       PolylinePointMode, Polyline, Vertex)
        from ogr_gui.dialogs import BlockObjectDialog
        w = _window()
        obj = Boundary(polyline=Polyline(vertices=[
            Vertex(10, 5), Vertex(20, 6), Vertex(30, 6.5)]),
            btype=BoundaryType.BLOCK_SEARCH_OBJECT,
            block_object=BlockObjectSpec(BlockObjectKind.POLYLINE))
        w.project.boundaries.append(obj)
        try:
            dlg = BlockObjectDialog(obj, w)
            dlg.cbo_left.setCurrentIndex(
                dlg.cbo_left.findData(PolylinePointMode.SEGMENT))
            dlg.cbo_right.setCurrentIndex(
                dlg.cbo_right.findData(PolylinePointMode.END_POINT))
            assert w.apply_block_object_spec(obj.id, dlg.spec())
            now = next(b for b in w.project.boundaries if b.id == obj.id)
            assert now.block_object.left_point is PolylinePointMode.SEGMENT
            assert now.block_object.right_point is \
                PolylinePointMode.END_POINT
            w.command_stack.undo(w.project)
            now = next(b for b in w.project.boundaries if b.id == obj.id)
            assert now.block_object.left_point is PolylinePointMode.ANY
            dlg.close()
        finally:
            w.project.boundaries[:] = [b for b in w.project.boundaries
                                       if b.id != obj.id]

    def test_a_point_can_be_picked_and_is_drawn(self):
        from ogr_core.geometry import (Boundary, BoundaryType, Polyline,
                                       Vertex)
        from ogr_gui.canvas.graphics_items import BoundaryItem
        from PySide6.QtWidgets import QGraphicsItem
        w = _window()
        obj = Boundary(polyline=Polyline(vertices=[Vertex(12.0, 7.0)]),
                       btype=BoundaryType.BLOCK_SEARCH_OBJECT)
        w.project.boundaries.append(obj)
        try:
            idx = w.canvas._pick_boundary(12.0, 7.0)
            assert w.project.boundaries[idx] is obj
            item = BoundaryItem(obj)
            assert not item.path().isEmpty()
            assert item.flags() & \
                QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations
        finally:
            w.project.boundaries.remove(obj)
